### PR TITLE
Alphabetize podcast list

### LINKED ISSUE #48: Alphabetize podcast lists and remove duplicates
Some of the lists are out of order and need to be alphabetized again. 
Please go through each of the categories, and sort them in alphabetical order.
We also a have few duplicates. Once the lists are in order it will be easier to spot those duplicates and remove them. 

If you are interested in working on this issue, please comment below and it will be assigned to you.
If you are new to this repository, please read through the [contributing docs](https://github.com/thisdot/tech-podcasts/blob/main/CONTRIBUTING.md) first. 

**Please note: issues will be assigned on a first come basis. Please do not start work on this issue until it has been assigned to you.**

### PR DESCRIPTION
**Pull request by ShivamGarg2910**
closes #48

### CODE REVIEW

**Comment by ShivamGarg2910** [comment]
Hi @jdwilkin4, please review the list order.

**Review by jdwilkin4 — CHANGES_REQUESTED** [review]
Thank you for alphabetizing the list.
But there was a second component to the issue that you missed.

There are still duplicate podcasts in the list.
Now that the list is in order it will be easier to spot those duplicates and remove them.

Once you do that, then this is ready to be merged. 👍

**Comment by ShivamGarg2910** [comment]
Removed the duplicates.

**Review by jdwilkin4 — APPROVED** [review]
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

**Pull request merged**
